"""init db

Revision ID: 7f1d0adb631a
Revises: 52512cb8e882
Create Date: 2024-04-26 11:40:08.947905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1d0adb631a'
down_revision = '52512cb8e882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=18), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
